### ISSUE TITLE
Plugin Repository Structure

### ISSUE THREAD

**Issue by agung2001** [Alwafauzan/tes_wordpress#1]
Hi @Alwafauzan thx for submitting the test

if possible, to make it easier to review the plugin.
please only upload the core plugin folder into the repository
instead of the full public folder

thx 🙏

**Comment by Alwafauzan** [comment]
Hello, I have done what you instructed.
I left the "tes-modal" folder on the branch

**Comment by agung2001** [comment]
also, you didn't use the [Dot Framework](https://github.com/artistudioxyz/dot-framework) as base development for the plugin.
what we wanted to see in the test is the capability to learn a new framework and apply it to your workflow

if you're still interested in joining our team you can update and resubmit the plugin 
thank you 🙏
